apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: staging-eloyt-com
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-eloyt-com

    spec:
      containers:
      - name: staging-eloyt-com
        image: ${IMAGE_URI}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 15
