apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: staging-rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-rabbitmq
    spec:
      containers:
      - name: staging-rabbitmq
        image: ${IMAGE_URI}
        ports:
        - containerPort: 15671
        - containerPort: 15672
        - containerPort: 5671
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "rabbitmq"
        - name: RABBITMQ_DEFAULT_PASS
          value: "EloytRabbit123"
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
      imagePullSecrets:
      - name: eloyt-azure-registry-key
