apiVersion: v1
kind: Service
metadata:
  name: staging-rabbitmq
  labels:
    app: staging-rabbitmq
spec:
  ports:
    - name: port1
      port: 15671
    - name: port2
      port: 15672
    - name: port3
      port: 5671
    - name: port4
      port: 5672
  selector:
    app: staging-rabbitmq