version: '3'

services:
  load-balancer:
    image: nginx:alpine
    volumes:
      - ./services/load-balancer/nginx.conf:/etc/nginx/nginx.conf
      - ./services/load-balancer/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:433"

  eloyt-com:
    build: ./services/eloyt.com
    volumes:
      - ./services/eloyt.com:/opt/app:rw
    ports:
      - "8091:80"
    environment:
      EXPOSE_PORT: 80

  api-eloyt-com:
    build: ./services/api.eloyt.com
    volumes:
      - ./services/api.eloyt.com:/opt/app:rw
    ports:
      - "8090:80"
    links:
      - mongoDB
      - redis

  mongoDB:
    image: tutum/mongodb:3.2
    volumes:
      - ./services/mongo/logs:/var/log/mongodb
      - ./services/mongo/data:/var/lib/mongodb
      - ./services/mongo/data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: "eloyt-db"
      MONGODB_USER: "eloyt-usr"
      MONGODB_PASS: "987987987"

  adminer:
    image: adminer
    links:
      - postgresdb

  postgresdb:
    build: ./services/postgreSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "eloyt-usr"
      POSTGRES_PASSWORD: "987987987"
    volumes:
      - ./services/postgreSQL/data:/var/lib/postgresql/data

  redis:
    build: ./services/redis
    image: eloythub/redis
    ports:
      - "6379"
