version: '2'

services:
  load-balancer:
    image: nginx:alpine
    volumes:
      - ./services/load-balancer/nginx.conf:/etc/nginx/nginx.conf
      - ./services/load-balancer/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:433"

  eloyt-com:
    build: ./services/eloyt.com
    volumes:
      - ./services/eloyt.com:/opt/app:rw
    ports:
      - "8091:80"
    environment:
      EXPOSE_PORT: 80

  api-eloyt-com:
    build: ./services/api.eloyt.com
    volumes:
      - ./services/api.eloyt.com:/opt/app:rw
    ports:
      - "8090:80"
    environment:
      EXPOSE_PORT: 80
      MONGO_DB_USERNAME: "eloyt-usr"
      MONGO_DB_PASSWORD: "987987987"
      MONGO_DB_HOST: "mongoDB"
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABSE: "eloyt-db"
      GCLOUD_PROJECT_ID: "eloyt-149708"
      GCLOUD_STORAGE_BUCKET: "eloyt"
    links:
      - mongoDB
      - redis

  mongoDB:
    image: tutum/mongodb:3.2
    volumes:
      - ./services/mongo/logs:/var/log/mongodb
      - ./services/mongo/data:/var/lib/mongodb
      - ./services/mongo/data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: "eloyt-db"
      MONGODB_USER: "eloyt-usr"
      MONGODB_PASS: "987987987"

  redis:
    build: ./services/redis
    image: eloythub/redis
    ports:
      - "6379"
