version: '2'

services:
  api:
    build: ./docker/api
    image: eloythub/api
    volumes:
      - ./docker/api:/home/app/api
    ports: ["80"]
    environment:
      EXPOSE_PORT: 80
      MONGO_DB_USERNAME: ""
      MONGO_DB_PASSWORD: ""
      MONGO_DB_HOST: "mongoDB"
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABSE: "eloyt_idea_studio"
    links:
      - mongoDB
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports: ["80:80"]

  mongoDB:
    image: mongo:3.2
    volumes:
      - ./docker/mongo/conf/mongod.json:/etc/mongod.json
      - ./docker/mongo/logs:/var/log/mongodb
      - ./docker/mongo/data:/var/lib/mongodb
      - ./docker/mongo/data/db:/data/db
    ports:
      - "27017"
    command: -smallfiles -nojournal

  redis:
    build: ./docker/redis
    image: eloythub/redis
    ports:
      - "6379"
