version: '2'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - server1:server1
    ports:
      - "80:80"

  server1:
    build: ./app/server
    volumes:
      - ./app/server:/var/app/server
    links:
      - mongoDB
    ports:
      - "3000"

  mongoDB:
    image: mongo:3.2
    volumes:
      - ./docker/mongo:/var/lib/mongodb
      - ./docker/mongo/data:/data/db
    ports:
      - "27017"
    restart: always
