version: '2'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - api:server
    ports:
      - "80:80"

  server:
    build: ./docker/api
    volumes:
      - ./docker/api:/var/app/api
    links:
      - mongoDB

  mongoDB:
    image: mongo:3.2
    volumes:
      - ./docker/mongo:/var/lib/mongodb
      - ./docker/mongo/data:/data/db
    ports:
      - "27017"
    restart: always
