version: '2'

services:
  api:
    build: ./services/api.eloyt.com
    image: eloythub/api.eloyt.com
    volumes:
      - ./services/api.eloyt.com:/home/app/api.eloyt.com
    ports: ["80"]
    environment:
      EXPOSE_PORT: 80
      MONGO_DB_USERNAME: ""
      MONGO_DB_PASSWORD: ""
      MONGO_DB_HOST: "mongoDB"
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABSE: "eloyt"
    links:
      - mongoDB
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports: ["8090:80"]

  mongoDB:
    image: mongo:3.2
    volumes:
      - ./services/mongo/conf/mongod.json:/etc/mongod.json
      - ./services/mongo/logs:/var/log/mongodb
      - ./services/mongo/data:/var/lib/mongodb
      - ./services/mongo/data/db:/data/db
    ports:
      - "27017:27017"
    command: -smallfiles -nojournal

  redis:
    build: ./services/redis
    image: eloythub/redis
    ports:
      - "6379"
