version: '3'

services:
  load-balancer:
    image: nginx:alpine
    volumes:
      - ./services/load-balancer/nginx.conf:/etc/nginx/nginx.conf
      - ./services/load-balancer/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:433"

  api-eloyt-com:
    build: ./services/api.eloyt.com
    volumes:
      - ./services/api.eloyt.com:/opt/app:rw
    ports:
      - "8090:80"

  eloyt-com:
    build: ./services/eloyt.com
    volumes:
      - ./services/eloyt.com:/opt/app:rw
    ports:
      - "8091:80"
    environment:
      EXPOSE_PORT: 80

  com-eloyt-com:
    build: ./services/com.eloyt.com
    volumes:
      - ./services/com.eloyt.com:/opt/app:rw
    ports:
      - "8092:80"

  adminer:
    image: adminer
    links:
      - postgresdb

  postgresdb:
    build: ./services/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "eloyt-usr"
      POSTGRES_PASSWORD: "987987987"
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data

  redis:
    build: ./services/redis
    volumes:
      - ./services/redis/data:/data
