version: '2'

services:
  api:
    build: ./docker/api
    image: eloythub/api
    volumes:
      - ./docker/api:/home/app/api
    ports: ["80"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports: ["80:80"]

  mongoDB:
    image: mongo:3.2
    volumes:
      - ./docker/mongo:/var/lib/mongodb
      - ./docker/mongo/data:/data/db
    ports:
      - "27017"
    restart: always
