#!/bin/bash

DEFAULT_TAG="staging-v4"
GCLOUD_PROJECT_ID="eloyt-149708"

DOCKER_LOCAL_IMAGE="eloyt/api.eloyt.com"
DOCKER_GCLOUD_IMAGE="asia.gcr.io/$GCLOUD_PROJECT_ID/api.eloyt.com"

cd services/api.eloyt.com

docker build . -f Dockerfile.prod -t $DOCKER_LOCAL_IMAGE

docker tag $DOCKER_LOCAL_IMAGE $DOCKER_GCLOUD_IMAGE:$DEFAULT_TAG

gcloud docker -- push $DOCKER_GCLOUD_IMAGE:$DEFAULT_TAG

cd -