apiVersion: v1
kind: ReplicationController
metadata:
  name: el-letsencrypt
  labels:
    app: el-letsencrypt
  namespace: api
spec:
  replicas: 1
  selector:
    app: el-letsencrypt
  template:
    metadata:
      name: el-letsencrypt
      labels:
        app: el-letsencrypt
    spec:
      containers:
      - name: el-letsencrypt
        image: asia.gcr.io/${GCLOUD_PROJECT_ID}/certbot:${DEFAULT_TAG}
        ports:
        - containerPort: 443
        volumeMounts:
          - mountPath: /data
            name: public-claim-storage
      volumes:
        - name: public-claim-storage
          persistentVolumeClaim:
            claimName: el-public-pvc