apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: el-letsencrypt
  labels:
    name: el-letsencrypt
spec:
  ports:
  - port: 443
    name: http-secure
  selector:
    app: el-letsencrypt