apiVersion: v1
kind: ReplicationController
metadata:
  name: load-balancer
  labels:
    app: load-balancer
  namespace: api
spec:
  replicas: 1
  selector:
    app: load-balancer
  template:
    metadata:
      name: load-balancer
      labels:
        app: load-balancer
    spec:
      containers:
      - name: load-balancer
        image: asia.gcr.io/eloyt-149708/load-balancer:staging-v1
        ports:
        - containerPort: 80