apiVersion: v1
kind: ReplicationController
metadata:
  name: el-rc-mongo
  labels: 
    app: el-rc-mongo
  namespace: api
spec:
  replicas: 1
  selector:
    app: el-mongo
  template:
    metadata:
      name: el-mongo
      labels:
        app: el-mongo
    spec:
      containers:
      - image: mongo:3.2
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4