apiVersion: v1
kind: ReplicationController
metadata:
  name: el-redis
  labels:
    app: el-redis
  namespace: api
spec:
  replicas: 1
  selector:
    app: el-redis
  template:
    metadata:
      name: el-redis
      labels:
        app: el-redis
    spec:
      containers:
      - name: el-redis
        image: gcr.io/google_containers/redis:v1
        ports:
        - containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data/redis-db
      volumes:
        - name: redis-persistent-storage
          gcePersistentDisk:
            pdName: redis-disk
            fsType: ext4
