apiVersion: v1
kind: ReplicationController
metadata:
  name: eloyt-replication-controller
  labels: 
    app: api
  namespace: api
spec:
  replicas: 1
  selector:
    app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      volumes: 
      - name: storage
        hostPath:
          path: /tmp/eloyt/storage
      containers:
      - name: api
        image: asia.gcr.io/eloyt-149708/api.eloyt.com:staging-v1
        ports:
        - containerPort: 80
