apiVersion: v1
kind: ReplicationController
metadata:
  name: el-load-balancer
  labels:
    app: el-load-balancer
  namespace: api
spec:
  replicas: 1
  selector:
    app: el-load-balancer
  template:
    metadata:
      name: el-load-balancer
      labels:
        app: el-load-balancer
    spec:
      containers:
      - name: el-load-balancer
        image: asia.gcr.io/${GCLOUD_PROJECT_ID}/load-balancer:${DEFAULT_TAG}
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: http-secure
          containerPort: 443
          hostPort: 443
