apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: load-balancer
  labels:
    name: load-balancer
spec:
  type: LoadBalancer
  loadBalancerIP: 104.199.243.148
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: load-balancer