apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: staging-api-eloyt-com
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-api-eloyt-com

    spec:
      containers:
      - name: staging-api-eloyt-com
        image: ${IMAGE_URI}
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: staging
        - name: POSTGRES_DB_HOST
          value: 127.0.0.1
        - name: POSTGRES_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: POSTGRES_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        readinessProbe:
          httpGet:
            path: /health-check/database
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health-check/database
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          periodSeconds: 15

      - image: gcr.io/cloudsql-docker/gce-proxy:1.11
        name: cloudsql-proxy
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=e-stock-182503:asia-east1:postgres-staging=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql

      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: