apiVersion: v1
kind: ReplicationController
metadata:
  name: el-slack-deployer-bot
  labels:
    app: el-slack-deployer-bot
  namespace: api
spec:
  replicas: 1
  selector:
    app: el-slack-deployer-bot
  template:
    metadata:
      name: el-slack-deployer-bot
      labels:
        app: el-slack-deployer-bot
    spec:
      containers:
      - name: el-slack-deployer-bot
        image: asia.gcr.io/${GCLOUD_PROJECT_ID}/slack-deployer-bot:${DEFAULT_TAG}
        env:
        - name: REDIS_URL
          value: "redis://el-redis:6379/el"
        - name: HUBOT_SLACK_TOKEN
          value: ${HUBOT_SLACK_TOKEN}