apiVersion: v1
kind: PersistentVolume
metadata:
  name: el-storage-pv
  labels:
    app: el-storage-pv
  namespace: api
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: el-storage
    path: /data

