kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: el-storage-pvc
  labels:
    app: el-storage-pvc
  namespace: api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi