apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: el-storage
  labels:
    name: el-storage
spec:
  ports:
  - port: 2049
    name: storage-tcp-port-1
    protocol: TCP
  - port: 20048
    name: storage-tcp-port-2
    protocol: TCP
  - port: 111
    name: storage-tcp-port-3
    protocol: TCP
  - port: 111
    name: storage-udp-port
    protocol: UDP
  selector:
    app: el-storage