apiVersion: v1
kind: ReplicationController
metadata:
  name: el-eloyt-com
  labels:
    app: el-eloyt-com
  namespace: api
spec:
  replicas: 1
  selector:
    app: el-eloyt-com
  template:
    metadata:
      name: el-eloyt-com
      labels:
        app: el-eloyt-com
    spec:
      containers:
      - name: el-eloyt-com
        image: asia.gcr.io/${GCLOUD_PROJECT_ID}/eloyt.com:${DEFAULT_TAG}
        ports:
        - containerPort: 80