apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: el-mongo-public
  labels:
    app: el-mongo-public
spec:
  type: LoadBalancer
  loadBalancerIP: 104.199.218.233
  ports:
    - port: 27017
      name: http
  selector:
    app: el-mongo