FROM gcr.io/google_containers/redis:v1

MAINTAINER Mahan Hazrati<eng.mahan.hazrati@gmail.com>

COPY redis.conf /usr/local/etc/redis/redis.conf

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
